'use strict';
// Personal LAN/WireGuard search desk. Research data is held by the LXC.
const $=id=>document.getElementById(id);
fetch('release.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{$('version').textContent=d.version?`v${d.version}`:'Development';}).catch(()=>{$('version').textContent='Development';});
let currentDetails='';let gatheredDetails='';
function url(base,params){const u=new URL(base);for(const[k,v]of Object.entries(params))if(v!==''&&v!==null&&v!==undefined)u.searchParams.set(k,String(v));return u.href;}
function wiki(q,surname){return url('https://www.wikitree.com/index.php',{title:'Special:SearchPerson',wpSearch:1,wpFirst:q.first,wpLast:surname});}
function family(q,surname){return url('https://www.familysearch.org/search/record/results',{'q.givenName':q.first,'q.surname':surname});}
function createCard(name,note,links){const card=document.createElement('article');card.className='site';const title=document.createElement('strong');title.textContent=name;const text=document.createElement('span');text.textContent=note;const group=document.createElement('div');group.className='site-links';for(const[label,href]of links){const a=document.createElement('a');a.textContent=label+' ↗';a.href=href;a.target='_blank';a.rel='noopener noreferrer';group.append(a);}card.append(title,text,group);return card;}
$('search-form').addEventListener('submit',async e=>{e.preventDefault();const q=Object.fromEntries([...new FormData(e.currentTarget)].map(([k,v])=>[k,String(v).trim()]));$('error').hidden=true;if(!q.last){$('error').textContent='Enter a surname.';$('error').hidden=false;return;}const variants=q.variants.split(',').map(s=>s.trim()).filter(Boolean);if(variants.length>2){$('error').textContent='Use up to two additional surname spellings.';$('error').hidden=false;return;}const surnames=[...new Set([q.last,...variants])];const name=[q.first,q.last].filter(Boolean).join(' ');$('search-title').textContent='Searches for '+name;
const names=surnames.map(s=>[s,wiki(q,s)]);
const providers=[
['WikiTree','Contributed family-tree profiles. Names are prefilled. Add dates, birthplace and parents on the site using your search details below; confirm claims against cited records.',names],
['FamilySearch','Free historical-record search; a free account may be required. Names prefilled. Add your dates, places and relatives on the site. Some images have access restrictions.',surnames.map(s=>[s,family(q,s)])],
['FreeBMD','Free England and Wales birth, marriage and death indexes. Enter the search details on the provider’s form.',[['Open search','https://www.freebmd.org.uk/search']]],
['FreeREG','Free parish-register transcriptions. Enter the search details on the provider’s form.',[['Open search','https://www.freereg.org.uk/']]],
['FreeCEN','Free census transcriptions. Enter the search details on the provider’s form.',[['Open search','https://www.freecen.org.uk/']]],
['FIBIS','Free names and transcriptions for British India research, useful for India and Burma connections. Enter the search details on the provider’s form.',[['Open database','https://search.fibis.org/bin/index.php']]],
['The National Archives','Free archive catalogue descriptions; copies or downloads may cost. Names prefilled. Add dates and places on the site.',surnames.map(s=>[s,url('https://discovery.nationalarchives.gov.uk/results/r',{'_q':[q.first,s].filter(Boolean).join(' ')})])]
];$('sources').replaceChildren(...providers.map(p=>createCard(...p)));
currentDetails=`Name: ${name}\nOther surnames: ${variants.join(', ')||'None entered'}\nBirth year: ${q.birth||'Unknown'} (±${q.spread} years)\nDeath year: ${q.death||'Unknown'} (±${q.spread} years)\nBirthplace: ${q.place||'Unknown'}\nFather: ${[q.fatherFirst,q.fatherLast].filter(Boolean).join(' ')||'Unknown'}\nMother: ${[q.motherFirst,q.motherLast].filter(Boolean).join(' ')||'Unknown'}\n\nCheck each provider’s filters before searching. Historical place names and boundaries may differ. Check source citations before accepting a match.`;$('details-text').value=currentDetails;$('copy-status').textContent='';$('searches').hidden=false;await runSearch(q);});
$('search-form').addEventListener('reset',()=>{$('searches').hidden=true;$('results').replaceChildren();activeSearch='';gatheredDetails='';$('error').hidden=true;$('sources').replaceChildren();$('details-text').value='';currentDetails='';});
$('details-text').addEventListener('focus',e=>e.target.select());
$('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(currentDetails);$('copy-status').textContent='Copied.';}catch{$('details-text').focus();$('details-text').select();$('copy-status').textContent='Press Ctrl+C, or use your phone’s Copy option.';}});
$('download').addEventListener('click',()=>{const href=URL.createObjectURL(new Blob([currentDetails+'\n\n'+gatheredDetails],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=href;a.download='genealogy-search-details.txt';a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);});

let backend='';let activeSearch='';let lastQuery=null;
try{backend=localStorage.getItem('genealogy-backend')||'';}catch{}
$('backend-address').value=backend;
function endpoint(path){return backend+ '/api'+path;}
async function api(path,body){const response=await fetch(endpoint(path),{method:body?'POST':'GET',credentials:'omit',headers:{'X-Genealogy-Request':'1',...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!response.ok){let message='Server request failed';try{const d=await response.json();message=typeof d.detail==='string'?d.detail:'Check the entered details.';}catch{}throw Error(message);}return response.json();}
function showError(e){$('error').textContent=e.message||'Connection failed. Check the backend address, network and HTTPS setup.';$('error').hidden=false;}
async function history(){const runs=await api('/searches');$('history').replaceChildren();for(const run of runs){const b=document.createElement('button');b.className='quiet';b.textContent=`${run.query.first_name||''} ${run.query.last_name} · ${run.count} results · ${new Date(run.created).toLocaleString('en-GB')}`;b.addEventListener('click',async()=>{try{const data=await api('/searches/'+run.id);lastQuery=data.query;const form=$('search-form');const map={first:'first_name',last:'last_name',birth:'birth_year',death:'death_year',spread:'spread',place:'place',variants:'variants',fatherFirst:'father_first',fatherLast:'father_last',motherFirst:'mother_first',motherLast:'mother_last'};for(const[k,v]of Object.entries(map))form.elements.namedItem(k).value=data.query[v]??'';lastQuery={...data.query,__search_id:run.id};form.requestSubmit();}catch(e){showError(e);}});$('history').append(b);}}
async function connected(){$('connection').hidden=true;$('desk').hidden=false;$('error').hidden=true;await history();}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const value=$('backend-address').value.trim();try{if(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('Use an HTTPS backend origin, without a path or credentials.');backend=u.origin;}else{backend='';if(location.hostname.endsWith('github.io'))throw Error('Enter the HTTPS backend address after your LXC is configured.');}await api('/state');try{localStorage.setItem('genealogy-backend',backend);}catch{}await connected();}catch(e){showError(e);}});
$('logout').addEventListener('click',async()=>{try{$('desk').hidden=true;$('connection').hidden=false;$('searches').hidden=true;$('results').replaceChildren();$('history').replaceChildren();activeSearch='';}catch(e){showError(e);}});
async function runSearch(q){const button=$('search-form').querySelector('button[type=submit]');button.disabled=true;button.textContent='Searching…';$('results').replaceChildren();try{const query={first_name:q.first,last_name:q.last,variants:q.variants,birth_year:q.birth?Number(q.birth):null,death_year:q.death?Number(q.death):null,spread:Number(q.spread),place:q.place,father_first:q.fatherFirst,father_last:q.fatherLast,mother_first:q.motherFirst,mother_last:q.motherLast};let data;if(lastQuery){data=await api('/searches/'+lastQuery.__search_id);lastQuery=null;}else data=await api('/search',query);renderResults(data);await history();}catch(e){showError(e);}finally{button.disabled=false;button.textContent='Search and gather results';}}
function renderResults(data){gatheredDetails=data.results.map(r=>`${r.name}\n${r.source} — ${r.kind}\nBirth: ${r.birth||'unknown'} ${r.birthplace||''}\nDeath: ${r.death||'unknown'} ${r.deathplace||''}\nSource: ${r.url}\n${[...(r.reasons||[]),...(r.conflicts||[]),...(r.unknown||[]),r.notes||'',...(r.observations||[]).map(o=>o.source+': '+o.notes+' '+o.url)].filter(Boolean).join('\n')}\nUnverified research lead.`).join('\n\n---\n\n');activeSearch=data.search_id;$('results').replaceChildren();const message=document.createElement('p');message.className=data.status==='ok'?'notice':'error';message.textContent=data.message;$('results').append(message);for(const item of data.results){const card=document.createElement('article');card.className='result';const title=document.createElement('h3');title.textContent=item.name;const source=document.createElement('p');source.className='source';source.textContent=item.source+' · '+item.kind;const facts=document.createElement('p');facts.textContent=`Birth: ${item.birth&&item.birth!=='0000-00-00'?item.birth:'unknown'} ${item.birthplace||''} · Death: ${item.death&&item.death!=='0000-00-00'?item.death:'unknown'} ${item.deathplace||''}`;const info=document.createElement('p');info.textContent=[...(item.reasons||[]),...(item.conflicts||[]),...(item.unknown||[]),item.notes||''].filter(Boolean).join(' / ');const a=document.createElement('a');a.href=item.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='View source ↗';card.append(source,title,facts);for(const text of item.reasons||[]){const p=document.createElement('p');p.className='reasons';p.textContent=text;card.append(p);}for(const text of item.conflicts||[]){const p=document.createElement('p');p.className='conflict';p.textContent=text;card.append(p);}info.textContent=[...(item.unknown||[]),item.notes||''].filter(Boolean).join(' / ');card.append(info,a);if(item.duplicate_count>1){const duplicates=document.createElement('p');duplicates.textContent=`${item.duplicate_count} repeated links grouped`;card.append(duplicates);}for(const observation of item.observations||[]){const p=document.createElement('p');p.textContent=`${observation.source}: ${observation.notes||observation.url}`;card.append(p);}$('results').append(card);}if(!data.results.length){const p=document.createElement('p');p.textContent=data.status==='ok'?'No public profiles returned. Try fewer filters or other record sources.':'No automatic results available; the saved search can still hold manually found evidence.';$('results').append(p);}}
$('lead-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;try{if(!activeSearch)throw Error('Search or open a saved search first.');const data=await api('/searches/'+activeSearch+'/leads',Object.fromEntries(new FormData(e.currentTarget)));renderResults(data);form.reset();await history();}catch(e){showError(e);}});
if(!location.hostname.endsWith('github.io')||backend)api('/state').then(connected).catch(()=>{});
