import React, {useState, useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

type Workspace={id:string;name:string;people:number};
type Report={people:number;families:number;sources:number;media_references:number;encoding:string;gedcom_version:string;warnings:string[];possible_duplicates?:number;other_zip_files?:string[];preservation:string};
type ImportItem={id:string;filename:string;status:string;report:Report;created:string};
type State={version:string;workspaces:Workspace[];imports:ImportItem[];providers:{name:string;type:string;status:string}[]};
type Person={id:string;name:string;birth:string;death:string;place:string;status:string};
type Citation={ref:string;title:string;page:string;text:string};
type PersonDetail=Person & {import_id:string;workspace_ids:string[];data:{names:string[];notes:string[];citations:Citation[];events:{type:string;date:string;place:string;value:string;citations:Citation[]}[]};relationships:{id:string;parent_id:string;child_id:string;role:string;person:Person;status:string;evidence:string}[]};
type Entry={id:string;person_id:string|null;kind:string;title:string;text:string;source_url:string;status:string;created:string};
type Document={id:string;filename:string;description:string;size:number;sha256:string;created:string};

async function api<T>(path:string, method='GET', body?:unknown):Promise<T>{
 const form=body instanceof FormData;
 const response=await fetch('/api'+path,{method,credentials:'same-origin',headers:{'X-Genealogy-Request':'1',...(!form&&body?{'Content-Type':'application/json'}:{})},body:body?form?body:JSON.stringify(body):undefined});
 if(!response.ok){let error='Request failed';try{const data=await response.json();error=typeof data.detail==='string'?data.detail:JSON.stringify(data.detail);}catch{} throw new Error(error);}
 return response.json();
}
const readable=(s:string)=>s==='imported_unverified'?'Imported · unverified':s==='reviewed'?'Reviewed':s;
const date=(s:string)=>new Date(s).toLocaleString('en-GB');
const eventNames:Record<string,string>={BIRT:'Birth',DEAT:'Death',BURI:'Burial',CHR:'Christening',BAPM:'Baptism',RESI:'Residence',CENS:'Census',OCCU:'Occupation',EMIG:'Emigration',IMMI:'Immigration',ADOP:'Adoption',EVEN:'Event',FACT:'Fact'};

function App(){
 const [state,setState]=useState<State|null>(null),[signed,setSigned]=useState(false),[initial,setInitial]=useState(true);
 const [password,setPassword]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [workspace,setWorkspace]=useState(''),[tab,setTab]=useState('People');
 const [query,setQuery]=useState(''),[place,setPlace]=useState(''),[year,setYear]=useState(''),[spread,setSpread]=useState('5'),[relative,setRelative]=useState('');
 const [people,setPeople]=useState<Person[]>([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[person,setPerson]=useState<PersonDetail|null>(null);
 const [entries,setEntries]=useState<Entry[]>([]),[documents,setDocuments]=useState<Document[]>([]),[audit,setAudit]=useState<{id:string;action:string;detail:unknown;created:string}[]>([]),[auditOffset,setAuditOffset]=useState(0);
 const [preview,setPreview]=useState<ImportItem|null>(null),[selectedWorkspaces,setSelectedWorkspaces]=useState<string[]>([]),[reviewed,setReviewed]=useState(false);
 const [entryKind,setEntryKind]=useState('note'),[title,setTitle]=useState(''),[text,setText]=useState(''),[source,setSource]=useState('');
 const [reviewRelation,setReviewRelation]=useState<PersonDetail['relationships'][number]|null>(null),[evidence,setEvidence]=useState(''),[relationChecked,setRelationChecked]=useState(false);
 const current=state?.workspaces.find(w=>w.id===workspace);
 async function refresh(){const s=await api<State>('/state');setState(s);setSigned(true);setWorkspace(w=>w||s.workspaces[0]?.id||'');return s;}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{refresh().catch(()=>setSigned(false)).finally(()=>setInitial(false));},[]);
 async function search(start=0){
  const p=new URLSearchParams({workspace_id:workspace,q:query,place,spread,relative,offset:String(start)});if(year)p.set('year',year);
  const result=await api<{people:Person[];total:number}>('/people?'+p);setPeople(result.people);setTotal(result.total);setOffset(start);
 }
 async function loadResearch(){
  const p=new URLSearchParams({workspace_id:workspace});if(person)p.set('person_id',person.id);
  const [e,d]=await Promise.all([api<Entry[]>('/entries?'+p),api<Document[]>('/documents?'+p)]);setEntries(e);setDocuments(d);
 }
 useEffect(()=>{if(workspace&&signed){setPerson(null);setReviewRelation(null);setQuery('');setPlace('');setYear('');setRelative('');api<{people:Person[];total:number}>('/people?workspace_id='+workspace).then(r=>{setPeople(r.people);setTotal(r.total);setOffset(0);}).catch(e=>setError(e.message));}},[workspace,signed]);
 useEffect(()=>{if(workspace&&signed)loadResearch().catch(e=>setError(e.message));},[workspace,person?.id,signed]);
 useEffect(()=>{if(tab==='Evidence log'&&signed)api<typeof audit>('/audit?offset='+auditOffset).then(setAudit).catch(e=>setError(e.message));},[tab,signed,auditOffset]);
 async function openPerson(id:string){setPerson(await api<PersonDetail>('/people/'+id));setReviewRelation(null);}
 function citations(items:Citation[]){return items.length?<div className="citations">{items.map((c,i)=><p key={i}><strong>Source:</strong> {c.title||c.ref}{c.page?' · '+c.page:''}{c.text?<><br/>{c.text}</>:null}</p>)}</div>:null;}
 if(initial)return <main className="login"><p>Opening your research…</p></main>;
 if(!signed)return <main className="login"><div className="brand-mark">G</div><p className="eyebrow">YOUR FAMILY RESEARCH</p><h1>Genealogy</h1><p>One place for your trees, evidence and unanswered questions.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/login','POST',{password});setPassword('');await refresh();});}}><label>Owner password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label><button disabled={busy}>Sign in</button></form>{error&&<p role="alert" className="error">{error}</p>}</main>;
 return <div className="app"><aside><div className="brand"><span className="brand-mark">G</span><div><strong>Genealogy</strong><small>Family research</small></div></div><label className="workspace-label">Research workspace<select value={workspace} onChange={e=>setWorkspace(e.target.value)}>{state?.workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><nav>{['People','Import tree','Research','Documents','Providers','Evidence log'].map(t=><button className={tab===t?'active':'quiet'} key={t} onClick={()=>{setTab(t);setError('');setMessage('');}}>{t}</button>)}</nav><div className="aside-foot"><small>Version {state?.version}</small><button className="quiet" disabled={busy} onClick={()=>run(async()=>{await api('/logout','POST');setSigned(false);setState(null);setPerson(null);setPeople([]);setEntries([]);setDocuments([]);})}>Sign out</button></div></aside>
 <main><header><div><p className="eyebrow">{current?.name} WORKSPACE</p><h1>{tab}</h1></div><span className="count">{current?.people||0} people</span></header>
 {error&&<div role="alert" className="error">{error}</div>}{message&&<div role="status" className="success">{message}</div>}
 {tab==='People'&&<><section className="panel"><h2>Search your tree</h2><form onSubmit={e=>{e.preventDefault();run(()=>search());}}><div className="grid search-grid"><label>Names or spelling variants<input placeholder="Gooding | Goodin" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Historical or current place<input placeholder="Burma, Rangoon, Barbados…" value={place} onChange={e=>setPlace(e.target.value)}/></label><label>Birth year<input type="number" min="1" max="2100" value={year} onChange={e=>setYear(e.target.value)}/></label><label>Years either side<input type="number" min="0" max="100" value={spread} onChange={e=>setSpread(e.target.value)}/></label><label>Parent or child’s name<input value={relative} onChange={e=>setRelative(e.target.value)}/></label></div><div className="row"><button disabled={busy}>Search</button><small>Searches imported names, dates and places. Use | between name variants. Historical aliases must be entered explicitly in this release.</small></div></form></section>
 <div className="people-layout"><section className="panel"><div className="row spread"><h2>{total} results</h2>{person&&<button className="quiet" onClick={()=>setPerson(null)}>Clear selection</button>}</div>{people.length===0?<div className="empty"><h3>Start with your existing tree</h3><p>Import your Ancestry GEDCOM or ZIP, review its report and choose the workspaces it belongs to.</p><button onClick={()=>setTab('Import tree')}>Import a tree</button></div>:people.map(p=><button className={'person-row '+(person?.id===p.id?'selected':'')} key={p.id} onClick={()=>run(()=>openPerson(p.id))}><strong>{p.name}</strong><span>{p.birth||'Birth unknown'}{p.death?' — '+p.death:''}</span><small>{p.place}</small><span className="badge">{readable(p.status)}</span></button>)}<div className="row spread"><button className="quiet" disabled={busy||offset===0} onClick={()=>run(()=>search(Math.max(0,offset-50)))}>Previous</button><small>{total?`${offset+1}–${Math.min(offset+50,total)}`:'0'}</small><button className="quiet" disabled={busy||offset+50>=total} onClick={()=>run(()=>search(offset+50))}>Next</button></div></section>
 <section className="panel detail">{!person?<div className="empty"><h2>Select a person</h2><p>Inspect their facts, citations and relationships before drawing conclusions.</p></div>:<><span className="badge">{readable(person.status)}</span><h2>{person.name}</h2><p>{person.data.names.join(' · ')}</p><div className="row"><button className="quiet" onClick={()=>setTab('Research')}>Notes & questions</button><button className="quiet" onClick={()=>setTab('Documents')}>Evidence files</button></div><label>Also include in workspace<select defaultValue="" key={person.id+person.workspace_ids.join()} onChange={e=>{const wid=e.target.value;if(wid)run(async()=>{await api('/people/'+person.id+'/workspaces','PUT',{workspace_ids:[wid]});await openPerson(person.id);await refresh();setMessage('Person added to the other workspace. Research notes remain in their original workspace.');});}}><option value="">Choose…</option>{state?.workspaces.filter(w=>!person.workspace_ids.includes(w.id)).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><h3>Life events</h3>{person.data.events.length===0&&<p>No interpreted events.</p>}{person.data.events.map((ev,i)=><article className="event" key={i}><strong>{eventNames[ev.type]||ev.type}</strong><p>{[ev.date,ev.place,ev.value].filter(Boolean).join(' · ')||'Details not recorded'}</p>{citations(ev.citations)}</article>)}{citations(person.data.citations)}<h3>Relationships</h3>{person.relationships.length===0&&<p>No parent or child relationships recorded.</p>}{person.relationships.map(r=><article className="event" key={r.id}><div className="row spread"><div><small>{r.role}</small><button className="link" onClick={()=>run(()=>openPerson(r.person.id))}>{r.person.name}</button><span className="badge">{readable(r.status)}</span></div><button className="quiet" onClick={()=>{setReviewRelation(r);setEvidence(r.evidence);setRelationChecked(false);}}>Review</button></div>{r.evidence&&<p>{r.evidence}</p>}</article>)}
 {reviewRelation&&<section className="review-box"><h3>Review this relationship</h3><p><strong>{reviewRelation.role==='Parent'?reviewRelation.person.name:person.name}</strong> is recorded as a parent of <strong>{reviewRelation.role==='Parent'?person.name:reviewRelation.person.name}</strong>.</p><label>Evidence and your reasoning<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} minLength={10}/></label><label className="check"><input type="checkbox" checked={relationChecked} onChange={e=>setRelationChecked(e.target.checked)}/>I reviewed this exact parent–child relationship.</label><button disabled={busy||!relationChecked||evidence.trim().length<10} onClick={()=>run(async()=>{await api('/relationships/review','POST',{parent_id:reviewRelation.parent_id,child_id:reviewRelation.child_id,evidence,reviewed:relationChecked});await openPerson(person.id);setMessage('Relationship review recorded.');})}>Record review</button><button className="quiet" onClick={()=>setReviewRelation(null)}>Cancel</button></section>}
 {person.data.notes.length>0&&<><h3>Imported notes</h3>{person.data.notes.map((n,i)=><p className="prewrap" key={i}>{n}</p>)}</>}<p><a href={'/api/imports/'+person.import_id+'/preserved'}>Download preserved tree data</a></p></> }</section></div></>}
 {tab==='Import tree'&&<><section className="panel"><h2>Bring in your Ancestry tree</h2><p>Upload a GEDCOM or its ZIP export. Nothing enters your person register until you review and accept the report.</p><p className="muted">Photos and certificates usually need separate uploads. The original export and all raw GEDCOM tags are retained. Maximum upload: 25 MiB.</p><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);run(async()=>{const result=await api<{id:string;status:string;report:Report;duplicate:boolean}>('/imports','POST',form);const s=await refresh();setPreview(s.imports.find(i=>i.id===result.id)||null);setSelectedWorkspaces([workspace]);setReviewed(false);if(result.duplicate)setMessage('This exact export is already stored; it has not been imported twice.');});}}><label>GEDCOM or ZIP<input name="file" type="file" accept=".ged,.gedcom,.zip" required/></label><button disabled={busy}>Preview import</button></form></section>
 {preview&&<section className="panel"><h2>{preview.filename}</h2><div className="stats"><div><strong>{preview.report.people}</strong><span>People</span></div><div><strong>{preview.report.families}</strong><span>Families</span></div><div><strong>{preview.report.sources}</strong><span>Source records</span></div><div><strong>{preview.report.media_references}</strong><span>Media references</span></div></div><p>GEDCOM {preview.report.gedcom_version} · {preview.report.encoding}</p><p>{preview.report.preservation}</p>{!!preview.report.possible_duplicates&&<p className="error">{preview.report.possible_duplicates} possible duplicates of existing people. A different export creates a separate snapshot; no automatic merge is performed.</p>}<ul>{preview.report.warnings.map((w,i)=><li key={i}>{w}</li>)}</ul><div className="row"><a href={'/api/imports/'+preview.id+'/original'}>Download original export</a><a href={'/api/imports/'+preview.id+'/preserved'}>Download preserved data</a></div>{preview.status==='preview'?<><h3>Include this tree in</h3>{state?.workspaces.map(w=><label className="check" key={w.id}><input type="checkbox" checked={selectedWorkspaces.includes(w.id)} onChange={e=>setSelectedWorkspaces(e.target.checked?[...selectedWorkspaces,w.id]:selectedWorkspaces.filter(x=>x!==w.id))}/>{w.name}</label>)}<label className="check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the report. Import the people and relationships as unverified claims.</label><button disabled={busy||!reviewed||!selectedWorkspaces.length} onClick={()=>run(async()=>{const result=await api<{people:number}>('/imports/'+preview.id+'/commit','POST',{workspace_ids:selectedWorkspaces,reviewed});const s=await refresh();setPreview(s.imports.find(i=>i.id===preview.id)||null);await search();setMessage(`${result.people} people imported as unverified claims.`);})}>Accept import</button></>:<p className="success">This import has already been accepted.</p>}</section>}
 <section className="panel"><h2>Stored imports</h2>{!state?.imports.length?<p>No exports uploaded yet.</p>:state.imports.map(i=><button className="person-row" key={i.id} onClick={()=>{setPreview(i);setReviewed(false);setSelectedWorkspaces([workspace]);}}><strong>{i.filename}</strong><small>{date(i.created)} · {i.report.people} people · {i.status}</small></button>)}</section></>}
 {(tab==='Research'||tab==='Documents')&&<section className="scope"><strong>{person?'For '+person.name:'Whole '+current?.name+' workspace'}</strong>{person&&<button className="quiet" onClick={()=>setPerson(null)}>Show whole workspace</button>}</section>}
 {tab==='Research'&&<><section className="panel"><h2>Save a note, question or possible match</h2><p>Possible matches stay in the research queue. Resolving a lead never adds people or relationships to your tree.</p><form onSubmit={e=>{e.preventDefault();run(async()=>{await api('/entries','POST',{workspace_id:workspace,person_id:person?.id||null,kind:entryKind,title,text,source_url:source});setTitle('');setText('');setSource('');await loadResearch();setMessage('Research entry saved.');});}}><div className="grid"><label>Entry type<select value={entryKind} onChange={e=>setEntryKind(e.target.value)}><option value="note">Research note</option><option value="question">Unanswered question</option><option value="lead">Possible match</option></select></label><label>Title<input value={title} maxLength={300} onChange={e=>setTitle(e.target.value)} required/></label></div><label>Evidence, observations and contradictions<textarea value={text} onChange={e=>setText(e.target.value)}/></label><label>Source link (optional)<input type="url" value={source} onChange={e=>setSource(e.target.value)} placeholder="https://…"/></label><button disabled={busy}>Save entry</button></form></section><section className="panel"><h2>Research queue</h2>{!entries.length?<p>No research entries in this view.</p>:entries.map(e=><article className="event" key={e.id}><span className="badge">{e.kind} · {e.status}</span><h3>{e.title}</h3><p className="prewrap">{e.text}</p>{e.source_url&&<p><a href={e.source_url} target="_blank" rel="noreferrer">Open source</a></p>}<small>{date(e.created)}</small><div className="row">{['open','resolved','rejected'].filter(s=>s!==e.status).map(s=><button className="quiet" disabled={busy} key={s} onClick={()=>run(async()=>{await api('/entries/'+e.id,'PATCH',{status:s});await loadResearch();})}>{s==='open'?'Reopen':s==='resolved'?'Mark resolved':'Reject lead'}</button>)}</div></article>)}</section></>}
 {tab==='Documents'&&<><section className="panel"><h2>Store your evidence</h2><p>Keep original certificates, record images and photographs with a description of their source. Files remain on the central installation.</p><form onSubmit={e=>{e.preventDefault();const el=e.currentTarget;const form=new FormData(el);form.set('workspace_id',workspace);form.set('person_id',person?.id||'');run(async()=>{await api('/documents','POST',form);el.reset();await loadResearch();setMessage('Evidence file stored.');});}}><label>Certificate, photograph or document<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.gif,.tif,.tiff,.txt" required/></label><label>Source and description<textarea name="description" placeholder="Repository, record reference, who supplied it, date obtained…"/></label><button disabled={busy}>Upload evidence</button></form></section><section className="panel"><h2>Stored documents</h2>{!documents.length?<p>No documents in this view.</p>:documents.map(d=><article key={d.id} className="event"><h3>{d.filename}</h3><p className="prewrap">{d.description}</p><p><a href={'/api/documents/'+d.id+'/download'}>Download original</a> · {(d.size/1024).toFixed(1)} KiB</p><small>{date(d.created)}</small><details><summary>File checksum</summary><code>{d.sha256}</code></details></article>)}</section></>}
 {tab==='Providers'&&<section className="panel"><h2>External search connections</h2><p>This release searches your imported tree and stores manual research leads. External API search is not enabled yet.</p>{state?.providers.map(p=><article className="event" key={p.name}><h3>{p.name}</h3><p>{p.type}</p><span className="badge">{p.status}</span></article>)}<p>Contributed tree profiles are research leads. Catalogue descriptions locate historical material; access to an image may require a separate visit, account or payment.</p></section>}
 {tab==='Evidence log'&&<section className="panel"><h2>Changes and research activity</h2><p>Import approvals, evidence uploads and relationship reviews are recorded here.</p>{audit.map(a=><article className="event" key={a.id}><strong>{a.action.replaceAll('_',' ')}</strong><small className="block">{date(a.created)}</small><details><summary>Recorded details</summary><pre>{JSON.stringify(a.detail,null,2)}</pre></details></article>)}{!audit.length&&<p>No activity on this page.</p>}<div className="row spread"><button className="quiet" disabled={!auditOffset} onClick={()=>setAuditOffset(Math.max(0,auditOffset-100))}>Previous</button><button className="quiet" disabled={audit.length<100} onClick={()=>setAuditOffset(auditOffset+100)}>Older activity</button></div></section>}
 <footer>Sources first. Review every relationship. Your research is saved centrally.</footer>
 </main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
